[logger]
level = "INFO"

[storage]
db = "db"
url = "postgres://calendar:calendar@postgres:5432/calendar"
timeout = 3

[httpserver]
host = "0.0.0.0"
port = 8080

[grpcserver]
host = "0.0.0.0"
port = 8002

[amqp]
host = "rabbitmq"
port = 5672
username = "guest"
password = "guest"
queue_name = "events-notify"

[scheduler]
notify_check_period_s = 10
remove_check_period_s = 600